---
checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
    - "tests/"
    - "vendor/"
coding_style:
    php:
        indentation:
            general:
                use_tabs: false
        spaces:
            around_operators:
                concatenation: true
                negation: false
build:
    cache:
        directories:
        - vendor/
    nodes:
        php54:
            environment:
                php: 5.4
        php55:
            environment:
                php: 5.5
        php56:
            environment:
                php: 5.6
        php70:
            environment:
                php: 7.0
        php71:
            environment:
                php: 7.1
        php72:
            environment:
                php: 7.2
        php73:
            environment:
                php: 7.3
    tests:
        override:
        - idle_timeout: 4800
          command: "./vendor/bin/phpunit tests"
