<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita41da282b90d213661e27c440aa04518
{
    public static $files = array (
        '26db35d0498c3af7562af33227309219' => __DIR__ . '/../..' . '/src/functions.php',
        '797af80c1143897800cef23f803c076f' => __DIR__ . '/../..' . '/src/CallRerouting/functions.php',
        '3d00ac85237afa0a95418be9d3a3d648' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/CallRerouting/functions.php',
        '1d274b725e04b0ac6e013fe3e951c9e7' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/CodeManipulation/functions.php',
        'a43c27a2843edc5ad3b9db9bac89488c' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/ConflictPrevention/functions.php',
        '90197d12814b7172e494d6f43b1fe244' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/Generic/functions.php',
        'c4e3053cd7b4dc5a595ad687b7cbef64' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/Namespaces/functions.php',
        'b19e7b29a0ee4825dd0f69974da4ff3f' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/RedefinitionOfInternals/functions.php',
        '20db11514444fca048dbed59fc33816e' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/RedefinitionOfLanguageConstructs/functions.php',
        '7b15434fd0bee2d043a7b1cfcbe1f6b6' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/RedefinitionOfNew/functions.php',
        '01c05e4b5de72b2ba165ec0ae0475356' => __DIR__ . '/../..' . '/src/CodeManipulation/functions.php',
        'f53fd7e076a00f64495dc3b5c216663c' => __DIR__ . '/../..' . '/src/Config/functions.php',
        '2c0c9c18b2971b96365f4ccaab50f99d' => __DIR__ . '/../..' . '/src/Redefinitions/LanguageConstructs/functions.php',
        '204f66c6fa9d6d4fcca84db2b6ce51d5' => __DIR__ . '/../..' . '/src/Stack/functions.php',
        '7335fc46393476f0de27165dc4aabd3c' => __DIR__ . '/../..' . '/src/Utils/functions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
