<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '26db35d0498c3af7562af33227309219' => $baseDir . '/src/functions.php',
    '797af80c1143897800cef23f803c076f' => $baseDir . '/src/CallRerouting/functions.php',
    '3d00ac85237afa0a95418be9d3a3d648' => $baseDir . '/src/CodeManipulation/Actions/CallRerouting/functions.php',
    '1d274b725e04b0ac6e013fe3e951c9e7' => $baseDir . '/src/CodeManipulation/Actions/CodeManipulation/functions.php',
    'a43c27a2843edc5ad3b9db9bac89488c' => $baseDir . '/src/CodeManipulation/Actions/ConflictPrevention/functions.php',
    '90197d12814b7172e494d6f43b1fe244' => $baseDir . '/src/CodeManipulation/Actions/Generic/functions.php',
    'c4e3053cd7b4dc5a595ad687b7cbef64' => $baseDir . '/src/CodeManipulation/Actions/Namespaces/functions.php',
    'b19e7b29a0ee4825dd0f69974da4ff3f' => $baseDir . '/src/CodeManipulation/Actions/RedefinitionOfInternals/functions.php',
    '20db11514444fca048dbed59fc33816e' => $baseDir . '/src/CodeManipulation/Actions/RedefinitionOfLanguageConstructs/functions.php',
    '7b15434fd0bee2d043a7b1cfcbe1f6b6' => $baseDir . '/src/CodeManipulation/Actions/RedefinitionOfNew/functions.php',
    '01c05e4b5de72b2ba165ec0ae0475356' => $baseDir . '/src/CodeManipulation/functions.php',
    'f53fd7e076a00f64495dc3b5c216663c' => $baseDir . '/src/Config/functions.php',
    '2c0c9c18b2971b96365f4ccaab50f99d' => $baseDir . '/src/Redefinitions/LanguageConstructs/functions.php',
    '204f66c6fa9d6d4fcca84db2b6ce51d5' => $baseDir . '/src/Stack/functions.php',
    '7335fc46393476f0de27165dc4aabd3c' => $baseDir . '/src/Utils/functions.php',
);
