<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Patchwork\\CallRerouting\\Decorator' => $baseDir . '/src/CallRerouting/Decorator.php',
    'Patchwork\\CallRerouting\\Handle' => $baseDir . '/src/CallRerouting/Handle.php',
    'Patchwork\\CallRerouting\\State' => $baseDir . '/src/CallRerouting/State.php',
    'Patchwork\\CodeManipulation\\Actions\\RedefinitionOfNew\\State' => $baseDir . '/src/CodeManipulation/Actions/RedefinitionOfNew/State.php',
    'Patchwork\\CodeManipulation\\Source' => $baseDir . '/src/CodeManipulation/Source.php',
    'Patchwork\\CodeManipulation\\State' => $baseDir . '/src/CodeManipulation/State.php',
    'Patchwork\\CodeManipulation\\Stream' => $baseDir . '/src/CodeManipulation/Stream.php',
    'Patchwork\\Config\\State' => $baseDir . '/src/Config/State.php',
    'Patchwork\\Exceptions\\CachePathConflict' => $baseDir . '/src/Exceptions/CachePathConflict.php',
    'Patchwork\\Exceptions\\CachePathUnavailable' => $baseDir . '/src/Exceptions/CachePathUnavailable.php',
    'Patchwork\\Exceptions\\CallbackException' => $baseDir . '/src/Exceptions/CallbackException.php',
    'Patchwork\\Exceptions\\ConfigException' => $baseDir . '/src/Exceptions/ConfigException.php',
    'Patchwork\\Exceptions\\ConfigKeyNotRecognized' => $baseDir . '/src/Exceptions/ConfigKeyNotRecognized.php',
    'Patchwork\\Exceptions\\ConfigMalformed' => $baseDir . '/src/Exceptions/ConfigMalformed.php',
    'Patchwork\\Exceptions\\DefinedTooEarly' => $baseDir . '/src/Exceptions/DefinedTooEarly.php',
    'Patchwork\\Exceptions\\Exception' => $baseDir . '/src/Exceptions/Exception.php',
    'Patchwork\\Exceptions\\InternalMethodsNotSupported' => $baseDir . '/src/Exceptions/InternalMethodsNotSupported.php',
    'Patchwork\\Exceptions\\InternalsNotSupportedOnHHVM' => $baseDir . '/src/Exceptions/InternalsNotSupportedOnHHVM.php',
    'Patchwork\\Exceptions\\NewKeywordNotRedefinable' => $baseDir . '/src/Exceptions/NewKeywordNotRedefinable.php',
    'Patchwork\\Exceptions\\NoResult' => $baseDir . '/src/Exceptions/NoResult.php',
    'Patchwork\\Exceptions\\NonNullToVoid' => $baseDir . '/src/Exceptions/NonNullToVoid.php',
    'Patchwork\\Exceptions\\NotUserDefined' => $baseDir . '/src/Exceptions/NotUserDefined.php',
    'Patchwork\\Exceptions\\StackEmpty' => $baseDir . '/src/Exceptions/StackEmpty.php',
    'Patchwork\\Stack\\State' => $baseDir . '/src/Stack/State.php',
    'Patchwork\\Utils\\State' => $baseDir . '/src/Utils/State.php',
);
