<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb7de713a68964186ce39fad9ae1c996a
{
    public static $files = array (
        '26db35d0498c3af7562af33227309219' => __DIR__ . '/../..' . '/src/functions.php',
        '797af80c1143897800cef23f803c076f' => __DIR__ . '/../..' . '/src/CallRerouting/functions.php',
        '3d00ac85237afa0a95418be9d3a3d648' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/CallRerouting/functions.php',
        '1d274b725e04b0ac6e013fe3e951c9e7' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/CodeManipulation/functions.php',
        'a43c27a2843edc5ad3b9db9bac89488c' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/ConflictPrevention/functions.php',
        '90197d12814b7172e494d6f43b1fe244' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/Generic/functions.php',
        'c4e3053cd7b4dc5a595ad687b7cbef64' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/Namespaces/functions.php',
        'b19e7b29a0ee4825dd0f69974da4ff3f' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/RedefinitionOfInternals/functions.php',
        '20db11514444fca048dbed59fc33816e' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/RedefinitionOfLanguageConstructs/functions.php',
        '7b15434fd0bee2d043a7b1cfcbe1f6b6' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/RedefinitionOfNew/functions.php',
        '01c05e4b5de72b2ba165ec0ae0475356' => __DIR__ . '/../..' . '/src/CodeManipulation/functions.php',
        'f53fd7e076a00f64495dc3b5c216663c' => __DIR__ . '/../..' . '/src/Config/functions.php',
        '2c0c9c18b2971b96365f4ccaab50f99d' => __DIR__ . '/../..' . '/src/Redefinitions/LanguageConstructs/functions.php',
        '204f66c6fa9d6d4fcca84db2b6ce51d5' => __DIR__ . '/../..' . '/src/Stack/functions.php',
        '7335fc46393476f0de27165dc4aabd3c' => __DIR__ . '/../..' . '/src/Utils/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Patchwork\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Patchwork\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Patchwork\\CallRerouting\\Decorator' => __DIR__ . '/../..' . '/src/CallRerouting/Decorator.php',
        'Patchwork\\CallRerouting\\Handle' => __DIR__ . '/../..' . '/src/CallRerouting/Handle.php',
        'Patchwork\\CallRerouting\\State' => __DIR__ . '/../..' . '/src/CallRerouting/State.php',
        'Patchwork\\CodeManipulation\\Actions\\RedefinitionOfNew\\State' => __DIR__ . '/../..' . '/src/CodeManipulation/Actions/RedefinitionOfNew/State.php',
        'Patchwork\\CodeManipulation\\Source' => __DIR__ . '/../..' . '/src/CodeManipulation/Source.php',
        'Patchwork\\CodeManipulation\\State' => __DIR__ . '/../..' . '/src/CodeManipulation/State.php',
        'Patchwork\\CodeManipulation\\Stream' => __DIR__ . '/../..' . '/src/CodeManipulation/Stream.php',
        'Patchwork\\Config\\State' => __DIR__ . '/../..' . '/src/Config/State.php',
        'Patchwork\\Exceptions\\CachePathConflict' => __DIR__ . '/../..' . '/src/Exceptions/CachePathConflict.php',
        'Patchwork\\Exceptions\\CachePathUnavailable' => __DIR__ . '/../..' . '/src/Exceptions/CachePathUnavailable.php',
        'Patchwork\\Exceptions\\CallbackException' => __DIR__ . '/../..' . '/src/Exceptions/CallbackException.php',
        'Patchwork\\Exceptions\\ConfigException' => __DIR__ . '/../..' . '/src/Exceptions/ConfigException.php',
        'Patchwork\\Exceptions\\ConfigKeyNotRecognized' => __DIR__ . '/../..' . '/src/Exceptions/ConfigKeyNotRecognized.php',
        'Patchwork\\Exceptions\\ConfigMalformed' => __DIR__ . '/../..' . '/src/Exceptions/ConfigMalformed.php',
        'Patchwork\\Exceptions\\DefinedTooEarly' => __DIR__ . '/../..' . '/src/Exceptions/DefinedTooEarly.php',
        'Patchwork\\Exceptions\\Exception' => __DIR__ . '/../..' . '/src/Exceptions/Exception.php',
        'Patchwork\\Exceptions\\InternalMethodsNotSupported' => __DIR__ . '/../..' . '/src/Exceptions/InternalMethodsNotSupported.php',
        'Patchwork\\Exceptions\\InternalsNotSupportedOnHHVM' => __DIR__ . '/../..' . '/src/Exceptions/InternalsNotSupportedOnHHVM.php',
        'Patchwork\\Exceptions\\NewKeywordNotRedefinable' => __DIR__ . '/../..' . '/src/Exceptions/NewKeywordNotRedefinable.php',
        'Patchwork\\Exceptions\\NoResult' => __DIR__ . '/../..' . '/src/Exceptions/NoResult.php',
        'Patchwork\\Exceptions\\NonNullToVoid' => __DIR__ . '/../..' . '/src/Exceptions/NonNullToVoid.php',
        'Patchwork\\Exceptions\\NotUserDefined' => __DIR__ . '/../..' . '/src/Exceptions/NotUserDefined.php',
        'Patchwork\\Exceptions\\StackEmpty' => __DIR__ . '/../..' . '/src/Exceptions/StackEmpty.php',
        'Patchwork\\Stack\\State' => __DIR__ . '/../..' . '/src/Stack/State.php',
        'Patchwork\\Utils\\State' => __DIR__ . '/../..' . '/src/Utils/State.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb7de713a68964186ce39fad9ae1c996a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb7de713a68964186ce39fad9ae1c996a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb7de713a68964186ce39fad9ae1c996a::$classMap;

        }, null, ClassLoader::class);
    }
}
