name: Turn tag into release

on:
  push:
    tags:
      - '*.*.*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    name: Bundle PHAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: exif, phar, openssl
          coverage: none
          ini-values: phar.readonly=Off, error_reporting=-1, display_errors=On, zend.assertions=1

      - name: Install Box
        run: composer global require humbug/box

      - name: Validate configuration
        run: box validate -i box.json

      - name: Build PHAR
        run: box compile -v --config=box.json

      - name: Display PHAR info via Box
        run: box info -l patchwork.phar

      - uses: actions/upload-artifact@v2
        with:
          name: phar
          path: ./patchwork.phar

  publish:
    name: Add PHAR to release
    runs-on: ubuntu-latest
    needs:
      - bundle

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: phar

      - name: Draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload PHAR as release asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: patchwork.phar

  regenerate-pages:
    name: Trigger update of GitHub Pages branch
    runs-on: ubuntu-latest
    needs:
      - publish
    
    steps:
      - name: Push empty commit to gh-pages
        run: |
          git config --global user.name antecedent
          git config --global user.email ignas.rudaitis@gmail.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/antecedent/patchwork.git"
          git fetch gh-token && git fetch gh-token gh-pages:gh-pages
          cd patchwork
          git commit --allow-empty -m "Deploy version ${{ github.ref }}"
          git push gh-token gh-pages
